### PR TITLE
Merge cdt/1.4.0 into all the good stuff from 1.3.x

### PR DESCRIPTION
**Pull request by tavisrudd**
Hi Phil,
I've merged the 1.4.0 master branch (with CDT support) into 1.3.x.  Everything appears to work for me in Emacs 24, although the CDT breakpoint backtraces don't currently support clj-stacktrace or color. If no breakpoint is set, the sldb backtraces appear to be identical to those in 1.3.4-SNAPSHOT.
Cheers,
Tavis

### CODE REVIEW

**Comment by technomancy** [comment]
Hmm... actually my plan was to release 1.3.4 as-is and then merge it all into the master branch once the underlying cdt library got a stable release. Would that work for you?

**Comment by tavisrudd** [comment]
I figured you'd want to release 1.3.4 as is so I bumped the version number in the merge up to 1.5.0.  Although the pull request is against 1.3.x (guess GH just chooses the current default branch) I meant for it to be on master. The version numbers don't really make any difference to me, but it is less than ideal to have two long-lived divergent branches.

@GeorgeJahad is there anything preventing a stable release of CDT right now?  I see that the clojar version is from Nov but the version on github was last updated in April. I think the tools.jar issue needs documenting properly.

**Comment by technomancy** [comment]
Great; once I get 1.3.4 out I'll merge this into master and drop the
version back to 1.4.0-SNAPSHOT.

Definitely want to get better documentation on tools.jar (or better yet,
a workaround to make manual tweaking unnecessary) before cutting a
release of 1.4.0.

**Comment by tavisrudd** [comment]
Cool. Just looking into that now (the workaround) and making sure this won't cause trouble for people without tools.jar in the right place if they aren't even using cdt.

**Comment by tavisrudd** [comment]
I've confirmed that it doesn't cause any trouble for non-cdt users.  

Would you object to 'lein plugin install swank-clojure' setting up the appropriate symlinks for tools.jar and sa-jdi.jar?  Sticking them in ~/.lein/plugins/ works fine.  clojure-jack-in is another spot this could be done.

**Comment by technomancy** [comment]
> Would you object to 'lein plugin install swank-clojure' setting up the
> appropriate symlinks for tools.jar and sa-jdi.jar?

There's not really any way for plugins to perform extra actions at
install-time. In addition, users can have multiple JDKs installed, and
it's my understanding that tools.jar files are incompatible across JDKs,
but switching JDKs after swank is installed needs to be supported.

**Comment by technomancy** [comment]
It's possible that we may just need special handling in Leiningen itself for tools.jar. I'm just not seeing a clean way to handle it.

**Comment by tavisrudd** [comment]
How about adding an env-var controlled option to the lein shell script that adds tools.jar and sa-jdi.jar to the classpath when enabled? clojure-jack-in could set the var when calling 'lein jack-in'.  That seems a bit cleaner than explicitly intercepting calls to 'lein swank' and 'lein jack-in' in the shell script.

**Comment by technomancy** [comment]
Does tools.jar need to be in Leiningen's classpath or just the project's? If the latter it could go in project.clj or the user's init.clj.

**Comment by tavisrudd** [comment]
I think just the project's. I was forgetting about the subproc, eval-in-project, etc. 

Rather than putting this in project.clj or init.clj, wouldn't it be better to inject it to the project's classpath dynamically so it can take into account the JDK version and use the right jars? Can a plugin task function, like swank, append to the project's :extra-classpath-dirs?

**Comment by technomancy** [comment]
Yeah, actually as long as the path to tools.jar can be reliably determined, associng an :extra-classpath-dirs key into the project map should work.

**Comment by tavisrudd** [comment]
Done.  It does nothing if the jars aren't found.  I have no idea how portable this is.  

The misleading warning from cdt "unabled to add tools.jar to classpath.This may cause CDT initialization to fail." will need removing and the docs still need updating.

**Comment by technomancy** [comment]
The heuristic for finding tools.jar doesn't work on Debian; it looks in `/usr/lib/jvm/java-6-openjdk/jre/lib` when it should be in `/usr/lib/jvm/java-6-openjdk/lib`. Basically `java.home` has slapped an extra `jre` directory that needs to be removed. What's a good cross-platform way to handle both cases?

**Comment by tavisrudd** [comment]
Ok.  I'll fix that up.  It looks like the structure is same on *nix's and Windows:
http://docs.oracle.com/javase/6/docs/technotes/tools/windows/jdkfiles.html
http://docs.oracle.com/javase/6/docs/technotes/tools/solaris/jdkfiles.html

**Comment by technomancy** [comment]
I had to add in `:jvm-opts` as well before I could get it to work. I went ahead and merged it with the paths that work for Debian's OpenJDK, but we'll want to do a bit more digging to figure out a solution that's cross-platform.

Thanks!

**Comment by technomancy** [comment]
Just added you as a committer, so feel free to put it straight on master.

**Comment by tavisrudd** [comment]
Thanks.  I've also got some commits that add clj-stacktrace/color support for cdt stacktraces and a somewhat hacky implementation of sldb locals for cdt.

**Comment by GeorgeJahad** [comment]
sorry, i've been out of the loop.  I'm busy working on something else till Thursday, and then should be able to help.

**Comment by tavisrudd** [comment]
Btw, if someone has :jvm-opts in ~/.lein/init.clj this will barf because of duplicate jvm-opt entries.  I've fixed the case where :jvm-opts comes from project.clj but I'm not sure how to handle the former.

**Comment by technomancy** [comment]
Conflict between `init.clj` and `project.clj` would probably be best fixed in Leiningen rather than in each plugin.

**Pull request closed without merging**
