### PR TITLE
clj-stacktrace support

### PR DESCRIPTION
**Pull request by dmansen**
Added support for clj-stacktrace output

### CODE REVIEW

**Comment by technomancy** [comment]
Excellent; I've been wanting this for a long time. Thanks!

Colors are probably pretty difficult since they're handled on the elisp side, but do you have any idea how difficult it would be to support clj-stacktrace's frame alignment as well?

**Comment by dmansen** [comment]
I have no clue at all, but let me look into that and get back to you

**Comment by dmansen** [comment]
Oh, do you mean the textual alignment and spacing? Printing it with indentation like clj-stacktrace does? I started playing around with it and ran into some issues...it might take modifications to clj-stacktrace to get at the parts we would want

**Comment by technomancy** [comment]
Yeah, it looks like clj-stacktrace doesn't expose what we would need as a function. I have commit rights to clj-stacktrace, so I can release a new version that exposes alignment. Feel free to take a swing at it, or if you don't I'll probably give it a shot some time next week.

**Pull request merged**
