### PR TITLE
Bob autodoc

### PR DESCRIPTION
**Pull request by robewald**
Hello, I merged autodoc and used the slime rpc mechanism to make swank-clojure work with the latest slime from git://git.boinkor.net/slime.git

It doesn't do autodoc quite yet.

Comments appreciated :)

### CODE REVIEW

**Comment by scottjad** [comment]
Hey robewald, can you clarify what these patches do? If they only add RPC to keep autodoc from stalling, can you say why you defined autodoc in swank_arglists.clj instead of just calling arglist-for-echo-area?

For me, autodoc was already working using (slime-setup '(slime-fancy)) and latest slime from cvs. Is the git one different or are they synced?

Just yesterday I added highlighting of the current param, you can see http://github.com/technomancy/swank-clojure/commit/813ff517a787b348e2b3b2299a7deff5c3e7b505 and see comment for screenshot.

Unfortunately I didn't see your branch beforehand and I'm wondering now if there's something here I'm missing.

Also do you know how CL slime gives the function name in autodoc the font-lock-function-name-face? Is it as easy as highlighting was? :)

**Comment by scottjad** [comment]
robewald, I just rewrote my highlighting commit http://github.com/scottjad/swank-clojure/commit/c6d4e04a2073f6b599ac4be04ae1cbd4e780730d hopefully soon it will be in technomancy/swank-clojure

Maybe by changing arglists-for-fname to use RPC everything will keep working?

**Comment by robewald** [comment]
Hey scottjad, Thanks for your comments, I can't really look at your commits at the moment. Just a quick word on why I used the rpc stuff: The replacement of the %cursor-marker% was done with regexps which affected unrelated stuff like (println "%cursor-marker%"). So I'll have a look at your changes over the weekend and see what they do.

**Comment by fmsbeekmans** [comment]
Awesome, I've been waiting to be able to use clojure with the newest slime. Can you explain how to get this up and running?

Thanks, hopefully this makes it up into the master branch soon too.

**Comment by technomancy** [comment]
Slime has actually introduced incompatible changes since this pull request was submitted, so this won't help you with what you want. You might have better luck with ritz instead: https://github.com/pallet/ritz

I'm actually bringing my maintainership of swank-clojure to an end; all active development will be shifted over to [nrepl.el](https://github.com/kingtim/nrepl.el) and Ritz.

**Pull request closed without merging**
