### PR TITLE
Add clj-stacktrace color support

### PR DESCRIPTION
**Pull request by dmansen**
I added the color support, however, it interferes a bit with the standard 'restartable' face application (the builtins for ansi conversion set font-lock-face foreground-color; it seems that if we set the 'face' text property as well it overrides the font lock). Not sure how to resolve that, but it seems to work fine otherwise.

### CODE REVIEW

**Comment by dmansen** [comment]
Also submitted the necessary changes to clj-stacktrace as a pull request, not sure if you get notified of pulls on that repo

**Comment by technomancy** [comment]
I'm a bit hesitant with this one since it's essentially the start of a fork of slime. (Maybe a fork is the right thing to do, but I want to make sure we're intentional about it and ready to support the decision.) Up to now we've been using 100% stock slime. Really there are two separate problems: one of modifying slime.el itself, and one of making it look funny for users of the unmodified slime.

The former could be addressed by moving the changes to slime.el into a defadvice that's stored in another file. The second is trickier; basically we would need colorization to be optional and have some way to detect whether said defadvice is loaded in the current Emacs instance.

I'd be happy to brainstorm on IRC over this either tomorrow or this afternoon (US Pacific time).

**Comment by dmansen** [comment]
Ahh, okay, I wasn't sure about that part of it. Obviously, we should avoid forking it if possible. I'll join the IRC from work tomorrow, just sent me a PM to catch my attention and emacs will let me know.

**Comment by dmansen** [comment]
Alright, I'm reasonably happy with the way this works now. If, at load time, we don't load the file "swank-color" with the advice, we don't use color support. Let me know if I'm doing anything gross or unnecessary :)

**Comment by technomancy** [comment]
Looks good; just wondering if there's a reason the color flag gets passed so far down into the control loop instead of getting set higher up in the call stack.

**Comment by dmansen** [comment]
No reason, just a momentary lapse in judgement. Fixed

**Pull request merged**
