### PR TITLE
Make M-. on namespace names jump to corresponding file, not throw a ClassNotFoundException

### PR DESCRIPTION
**Pull request by purcell**
The result of (ns-resolve _ns_ 'clojure.core) is a ClassNotFoundException, which causes swank.commands.basic/find-definitions-for-emacs to blow up when the user presses "M-." on a namespace name, e.g. inside a :use clause.

The attached patch fixes this, with the result that one can now jump directly to the file in which a namespace is defined.

-Steve

### CODE REVIEW

**Comment by scottjad** [comment]
Nice patch. Will pull when fork queue updates. Want to be added to technomancy/swank-clojure?

**Comment by purcell** [comment]
Cool, thanks, & yes please.

**Comment by technomancy** [comment]
Thanks; I've been wanting this for a while.

**Comment by purcell** [comment]
I've taken the liberty of pushing a follow-up commit which tidies this code up, and adds support for jumping to namespaces via their :as aliases: http://github.com/technomancy/swank-clojure/commit/c2386452f432222c5500a64f671faa85ac3569bf

**Pull request merged**
